
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kevin
 */
public class logincafe extends javax.swing.JFrame {

    /**
     * Creates new form logincafe
     */
    public logincafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        textoE = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        textoINI = new javax.swing.JLabel();
        textoUsr = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textoUsr1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnINI = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Café");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/logo.png"))); // NOI18N
        logo.setText("jLabel1");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, 130));

        textoE.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        textoE.setForeground(new java.awt.Color(0, 102, 102));
        textoE.setText("Café El Dorado");
        textoE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(textoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, 40));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/favicon.png"))); // NOI18N
        getContentPane().add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 50));

        textoINI.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        textoINI.setText("INICIAR SESIÓN");
        getContentPane().add(textoINI, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 250, 30));

        textoUsr.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        textoUsr.setText("Usuario:");
        getContentPane().add(textoUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 200, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 440, 50));

        textoUsr1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        textoUsr1.setText("Contraseña:");
        getContentPane().add(textoUsr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 200, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 430, 50));

        btnINI.setFont(new java.awt.Font("OCR A Extended", 0, 10)); // NOI18N
        btnINI.setText("Iniciar Sesión");
        btnINI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnINI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnINIMouseEntered(evt);
            }
        });
        btnINI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINIActionPerformed(evt);
            }
        });
        getContentPane().add(btnINI, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 120, 60));

        txtuser.setForeground(new java.awt.Color(153, 153, 153));
        txtuser.setText("Ingresar nombre de usuario");
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 220, 30));

        txtpass.setForeground(new java.awt.Color(102, 102, 102));
        txtpass.setText("********");
        txtpass.setBorder(null);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnINIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINIMouseEntered
       
    }//GEN-LAST:event_btnINIMouseEntered

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
 if (txtuser.getText().equals("Ingresar nombre de usuario")){
     txtuser.setText("");
     txtuser.setForeground(Color.black);
     }
     if (String.valueOf(txtpass.getPassword()).isEmpty()){
        txtpass.setText("********");
        txtuser.setForeground(Color.gray);
       }       
    }//GEN-LAST:event_txtuserMousePressed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
  if (String.valueOf(txtpass.getPassword()).equals("********")){
         txtpass.setText("");
         txtpass.setForeground(Color.black);
  }
  if (txtuser.getText().isEmpty()){
      txtuser.setText("Ingresar nombre de usuario");
      txtuser.setForeground(Color.black);
  }
    }//GEN-LAST:event_txtpassMousePressed

    private void btnINIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINIActionPerformed
       String usuario=this.txtuser.getText();
       String password=this.txtpass.getText();
       if (usuario.equals("usuario1")&&password.equals("password")){
           sesionIni sesion1 = new sesionIni();
           sesion1.show();
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(this,"Usuario o contraseña errónea.","ERROR",JOptionPane.ERROR_MESSAGE);
        
    }
       
    }//GEN-LAST:event_btnINIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logincafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logincafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logincafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logincafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logincafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono;
    private javax.swing.JButton btnINI;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel textoE;
    private javax.swing.JLabel textoINI;
    private javax.swing.JLabel textoUsr;
    private javax.swing.JLabel textoUsr1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
